package Interfaz;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import Clases.Cuenta_Corriente;
import javax.swing.JOptionPane;
import Interfaz.Principal;

public class Nueva_Cuenta extends javax.swing.JFrame {

   public Nueva_Cuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreCuenta = new javax.swing.JLabel();
        txtNombreCuenta = new javax.swing.JTextField();
        lblNombreCuenta1 = new javax.swing.JLabel();
        lblNombreCuenta2 = new javax.swing.JLabel();
        cbxTipoMoneda = new javax.swing.JComboBox<>();
        lblNombreCuenta3 = new javax.swing.JLabel();
        txtInstitucion = new javax.swing.JTextField();
        lblLogoBanco = new javax.swing.JLabel();
        lblNombreCuenta4 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        btnCuentaNueva = new javax.swing.JButton();
        lblIconoMoneda = new javax.swing.JLabel();
        btnDefault = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar nueva cuenta corriente");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreCuenta.setFont(new java.awt.Font("8BIT WONDER", 0, 14)); // NOI18N
        lblNombreCuenta.setText("Nombre de la cuenta");

        txtNombreCuenta.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N

        lblNombreCuenta1.setFont(new java.awt.Font("8BIT WONDER", 0, 14)); // NOI18N
        lblNombreCuenta1.setText("Tipo de moneda");

        lblNombreCuenta2.setFont(new java.awt.Font("8BIT WONDER", 0, 14)); // NOI18N
        lblNombreCuenta2.setText("Balance Disponible");

        cbxTipoMoneda.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        cbxTipoMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una moneda", "Colon Costarricense", "Dolar Estadounidense" }));

        lblNombreCuenta3.setFont(new java.awt.Font("8BIT WONDER", 0, 14)); // NOI18N
        lblNombreCuenta3.setText("Institucion");

        txtInstitucion.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txtInstitucion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInstitucionFocusLost(evt);
            }
        });

        lblNombreCuenta4.setFont(new java.awt.Font("8BIT WONDER", 0, 14)); // NOI18N
        lblNombreCuenta4.setText("Fecha de Apertura");

        txtBalance.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txtBalance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBalanceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBalanceFocusLost(evt);
            }
        });

        txtFecha.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N

        btnCuentaNueva.setBackground(new java.awt.Color(0, 0, 204));
        btnCuentaNueva.setFont(new java.awt.Font("8BIT WONDER", 2, 12)); // NOI18N
        btnCuentaNueva.setForeground(new java.awt.Color(255, 255, 255));
        btnCuentaNueva.setText("Crear cuenta");
        btnCuentaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentaNuevaActionPerformed(evt);
            }
        });

        btnDefault.setBackground(new java.awt.Color(0, 0, 204));
        btnDefault.setFont(new java.awt.Font("8BIT WONDER", 2, 12)); // NOI18N
        btnDefault.setForeground(new java.awt.Color(255, 255, 255));
        btnDefault.setText("Default");
        btnDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefaultActionPerformed(evt);
            }
        });

        btnReturn.setBackground(new java.awt.Color(0, 0, 204));
        btnReturn.setFont(new java.awt.Font("8BIT WONDER", 2, 12)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(255, 255, 255));
        btnReturn.setText("Cerrar");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombreCuenta2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombreCuenta4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtInstitucion)
                    .addComponent(txtNombreCuenta, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreCuenta1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxTipoMoneda, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombreCuenta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblIconoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addComponent(lblNombreCuenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtFecha))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCuentaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLogoBanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNombreCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxTipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 27, Short.MAX_VALUE)
                        .addComponent(lblNombreCuenta2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(lblIconoMoneda, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)))
                    .addComponent(lblLogoBanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblNombreCuenta3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNombreCuenta4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFecha)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCuentaNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInstitucionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInstitucionFocusLost
        if (this.txtInstitucion.getText().equals("Banco Nacional")){
            lblLogoBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_banco-nacional.png")));
        }
        if (this.txtInstitucion.getText().equals("Banco de Costa Rica")){
            lblLogoBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo BCR.png")));
        }
        if (this.txtInstitucion.getText().equals("Banco Popular")){
            lblLogoBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo-Banco-Popular.png")));
        }
        if (this.txtInstitucion.getText().equals("Banco Promerica")){
            lblLogoBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Banco-Promerica-Logo-1-7433.png")));
        }
        if (this.txtInstitucion.getText().equals("Bac Credomatic")){
            lblLogoBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bac_credomatic_logo.png")));
        }
        if (this.txtInstitucion.getText().equals("Coopenae")){
            lblLogoBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logos-PR-Coopenae.png")));
        }
        if (this.txtInstitucion.getText().equals("Coopeservidores")){
            lblLogoBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_cs.png")));
        }
        if (this.txtInstitucion.getText().equals("Davivienda")){
            lblLogoBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Davivienda-Logo.png")));
        }
    }//GEN-LAST:event_txtInstitucionFocusLost

    private void txtBalanceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBalanceFocusLost
        String balance = this.txtBalance.getText();
        if(!this.cbxTipoMoneda.getSelectedItem().equals("")){
            switch(this.cbxTipoMoneda.getSelectedItem().toString()){
                case "Colon Costarricense":
                    lblIconoMoneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono_Colon.png")));
                    break;
                case "Dolar Estadounidense":
                    lblIconoMoneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Icono_Dolar.png")));
                    break;
                default:
                    lblIconoMoneda.setIcon(null);
                    break;
            }
        }
        else{
            this.txtBalance.setText("");
            Border border = BorderFactory.createLineBorder(Color.RED, 2);
            this.txtBalance.setBorder(border);
        }
    }//GEN-LAST:event_txtBalanceFocusLost

    private void txtBalanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBalanceFocusGained
        this.txtBalance.setText("");
        Border border = BorderFactory.createLineBorder(Color.BLACK, 0);
        this.txtBalance.setBorder(border);
    }//GEN-LAST:event_txtBalanceFocusGained

    private void btnDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefaultActionPerformed
        this.txtBalance.setText("");
        this.txtFecha.setText("--/--/--");
        this.txtInstitucion.setText("");
        this.txtNombreCuenta.setText("");
        this.cbxTipoMoneda.setSelectedItem("Seleccione una moneda");
        this.lblLogoBanco.setIcon(null);
        this.lblIconoMoneda.setIcon(null);
    }//GEN-LAST:event_btnDefaultActionPerformed

    private void btnCuentaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentaNuevaActionPerformed
        String nombre = this.txtNombreCuenta.getText();
        String institucion = this.txtInstitucion.getText();
        String tipoMoneda = this.cbxTipoMoneda.getSelectedItem().toString();
        double balance = Double.parseDouble(this.txtBalance.getText());
        String fecha = this.txtFecha.getText();
        Cuenta_Corriente nueva_cuenta;
        try {
            nueva_cuenta = new Cuenta_Corriente(nombre, institucion, tipoMoneda, balance, fecha);
            JOptionPane.showMessageDialog(this, "Cuenta creada correctamente.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al crear la cuenta.\nPor favor revise los datos y trate nuevamente.");
        }
    }//GEN-LAST:event_btnCuentaNuevaActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        Principal principal = new Principal();
        this.setVisible(false);
        this.dispose();
        principal.setVisible(true);
    }//GEN-LAST:event_btnReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nueva_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nueva_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nueva_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nueva_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nueva_Cuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCuentaNueva;
    private javax.swing.JButton btnDefault;
    private javax.swing.JButton btnReturn;
    private javax.swing.JComboBox<String> cbxTipoMoneda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIconoMoneda;
    private javax.swing.JLabel lblLogoBanco;
    private javax.swing.JLabel lblNombreCuenta;
    private javax.swing.JLabel lblNombreCuenta1;
    private javax.swing.JLabel lblNombreCuenta2;
    private javax.swing.JLabel lblNombreCuenta3;
    private javax.swing.JLabel lblNombreCuenta4;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtInstitucion;
    private javax.swing.JTextField txtNombreCuenta;
    // End of variables declaration//GEN-END:variables
}
