/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 *
 * @author muril
 */
public class Nueva_Cuenta extends javax.swing.JFrame {

    /**
     * Creates new form Nueva_Cuenta
     */
    public Nueva_Cuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreCuenta = new javax.swing.JLabel();
        txtNombreCuenta = new javax.swing.JTextField();
        lblNombreCuenta1 = new javax.swing.JLabel();
        txtBalanceInicial = new javax.swing.JTextField();
        lblNombreCuenta2 = new javax.swing.JLabel();
        cbxTipoMoneda = new javax.swing.JComboBox<>();
        lblNombreCuenta3 = new javax.swing.JLabel();
        txtInstitucion = new javax.swing.JTextField();
        lblLogoBanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agregar nueva cuenta corriente");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreCuenta.setFont(new java.awt.Font("8BIT WONDER", 0, 14)); // NOI18N
        lblNombreCuenta.setText("Nombre de la cuenta");

        txtNombreCuenta.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N

        lblNombreCuenta1.setFont(new java.awt.Font("8BIT WONDER", 0, 14)); // NOI18N
        lblNombreCuenta1.setText("Tipo de moneda");

        txtBalanceInicial.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N

        lblNombreCuenta2.setFont(new java.awt.Font("8BIT WONDER", 0, 14)); // NOI18N
        lblNombreCuenta2.setText("Balance Disponible");

        cbxTipoMoneda.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        cbxTipoMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Colon Costarricense", "Dolar Estadounidense" }));

        lblNombreCuenta3.setFont(new java.awt.Font("8BIT WONDER", 0, 14)); // NOI18N
        lblNombreCuenta3.setText("Institucion");

        txtInstitucion.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txtInstitucion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtInstitucionFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtInstitucion)
                    .addComponent(lblNombreCuenta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombreCuenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNombreCuenta, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreCuenta1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBalanceInicial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(cbxTipoMoneda, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombreCuenta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblLogoBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNombreCuenta2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBalanceInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNombreCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbxTipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLogoBanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblNombreCuenta3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1190, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInstitucionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInstitucionFocusLost
        if (this.txtInstitucion.getText().equals("Banco Nacional")){
            lblLogoBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_banco-nacional.png")));
        }
        if (this.txtInstitucion.getText().equals("Banco de Costa Rica")){
            lblLogoBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo BCR.png")));
        }
        if (this.txtInstitucion.getText().equals("Banco Popular")){
            lblLogoBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo-Banco-Popular.png")));
        }
        if (this.txtInstitucion.getText().equals("Banco Promerica")){
            lblLogoBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Banco-Promerica-Logo-1-7433.png")));
        }
        if (this.txtInstitucion.getText().equals("Bac Credomatic")){
            lblLogoBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bac_credomatic_logo.png")));
        }
        if (this.txtInstitucion.getText().equals("Coopenae")){
            lblLogoBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logos-PR-Coopenae.png")));
        }
        if (this.txtInstitucion.getText().equals("Coopeservidores")){
            lblLogoBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_cs.png")));
        }
        if (this.txtInstitucion.getText().equals("Davivienda")){
            lblLogoBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Davivienda-Logo.png")));
        }
    }//GEN-LAST:event_txtInstitucionFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nueva_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nueva_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nueva_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nueva_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nueva_Cuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxTipoMoneda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogoBanco;
    private javax.swing.JLabel lblNombreCuenta;
    private javax.swing.JLabel lblNombreCuenta1;
    private javax.swing.JLabel lblNombreCuenta2;
    private javax.swing.JLabel lblNombreCuenta3;
    private javax.swing.JTextField txtBalanceInicial;
    private javax.swing.JTextField txtInstitucion;
    private javax.swing.JTextField txtNombreCuenta;
    // End of variables declaration//GEN-END:variables
}
